bt_navigator:
  ros__parameters:
    use_sim_time: False
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odom
    default_bt_xml_filename: "navigate_w_replanning_and_recovery.xml"
    plugin_lib_names:
    - nav2_compute_path_to_pose_action_bt_node
    - nav2_follow_path_action_bt_node
    - nav2_back_up_action_bt_node
    - nav2_spin_action_bt_node
    - nav2_wait_action_bt_node
    - nav2_clear_costmap_service_bt_node
    - nav2_is_stuck_condition_bt_node
    - nav2_goal_reached_condition_bt_node
    - nav2_goal_updated_condition_bt_node
    - nav2_initial_pose_received_condition_bt_node
    - nav2_reinitialize_global_localization_service_bt_node
    - nav2_rate_controller_bt_node
    - nav2_distance_controller_bt_node
    - nav2_speed_controller_bt_node
    - nav2_recovery_node_bt_node
    - nav2_pipeline_sequence_bt_node
    - nav2_round_robin_node_bt_node
    - nav2_transform_available_condition_bt_node
    - nav2_time_expired_condition_bt_node
    - nav2_distance_traveled_condition_bt_node

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: False    
      always_send_full_costmap: True
      footprint_padding: 0.10
      footprint: "[[0.3, 0.2], [0.3, -0.2], [-0.3, -0.2], [-0.3, 0.2]]"
      global_frame: map
      width: 8
      height: 8
      origin_x: 0.0
      origin_y: 0.0
      # plugins: ["voxel_layer", "inflation_layer"]
      plugins: ["stvl_obstacle_layer", "inflation_layer"]
      publish_frequency: 1.0
      resolution: 0.10
      robot_base_frame: base_link
      rolling_window: True
      track_unknown_space: False
      transform_tolerance: 0.3
      update_frequency: 5.0

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        enabled: True
        subscribe_to_updates: False
        map_topic: "/map"
        map_subscribe_transient_local: True
        track_unknown_space: False
        use_maximum: true
        unknown_cost_value: 0
        trinary_costmap: True
        transform_tolerance: 0.3

      # voxel_layer:
      #   plugin: "nav2_costmap_2d::VoxelLayer"
      #   enabled: True
      #   footprint_clearing_enabled: True
      #   max_obstacle_height: 2.0
      #   z_voxels: 20
      #   origin_z: 0.0
      #   z_resolution: 0.10
      #   unknown_threshold: 19
      #   publish_voxel_map: True
      #   mark_threshold: 2
      #   combination_method: 1
      #   publish_voxel_map: True

      #   # from obstacle_layer
      #   track_unknown_space: False
      #   transform_tolerance: 0.3
      #   observation_sources: pointcloud
      #   pointcloud:
      #     topic: /rslidar_points
      #     sensor_frame: rslidar
      #     observation_persistence: 0.0
      #     expected_update_rate: 0.3
      #     data_type: "PointCloud2"
      #     min_obstacle_height: 0.1
      #     max_obstacle_height: 2.0
      #     marking: True
      #     clearing: True
      #     obstacle_range: 2.5
      #     raytrace_range: 3.0

      stvl_obstacle_layer:
        plugin: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"
        observation_sources:   rslidar_points
        transform_tolerance:   0.3    # seconds  
        enabled:               true
        publish_voxel_map:     true   # default off  
        voxel_size:            0.1   #meters
        combination_method:    1      #1=max, 0=override
        mark_threshold:        0      #voxel height
        update_footprint_enabled: true
        track_unknown_space:   false   #default space is unknown
        decay_model:           0      #0=linear, 1=exponential, -1=persistent
        voxel_decay:           0.3     #seconds if linear, e^n if exponential
        mapping_mode:          false  # default off, saves map not for navigation
        map_save_duration:     60.0     #default 60s, how often to autosave

        rslidar_points:
          topic: /rslidar_points
          sensor_frame: rslidar
          observation_persistence: 0.5  #default 0, use all measurements taken during now-value, 0=latest 
          expected_update_rate: 0.1     #default 0, if not updating at this rate at least, remove from buffer
          data_type: PointCloud2
          min_obstacle_height: 0.15      #default 0, meters
          max_obstacle_height: 1.20      #defaule 3, meters
          inf_is_valid: false           #default false, for laser scans    
          marking: true
          clearing: false
          min_z: 0.2
          max_z: 3.0
          vertical_fov_angle: 0.56
          vertical_fov_padding: 0.0
          horizontal_fov_angle: 6.29
          decay_acceleration: 5.0
          filter: voxel               #default passthrough, apply "voxel", "passthrough", or no filter to sensor data, recommended to have at one filter on
          voxel_min_points: 3           #default 0, minimum points per voxel for voxel filter
          clear_after_reading: false    #default false, clear the buffer after the layer gets readings from it
          enabled: true
          model_type: 1
          obstacle_range: 4.0           #meters

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.3
        cost_scaling_factor: 10.0
        inflate_unknown: False
        inflate_around_unknown: False

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: False    
      always_send_full_costmap: True
      footprint_padding: 0.10
      footprint: "[[0.3, 0.2], [0.3, -0.2], [-0.3, -0.2], [-0.3, 0.2]]"
      global_frame: map
      width: 30
      height: 30
      origin_x: 0.0
      origin_y: 0.0
      # plugins: ["static_layer", "voxel_layer", "inflation_layer"]
      plugins: ["static_layer", "stvl_obstacle_layer", "inflation_layer"]
      publish_frequency: 2.0
      resolution: 0.10
      robot_base_frame: base_link
      rolling_window: True
      track_unknown_space: False
      transform_tolerance: 0.3
      update_frequency: 5.0

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        enabled: True
        subscribe_to_updates: True
        map_topic: "/map"
        map_subscribe_transient_local: True
        track_unknown_space: False
        use_maximum: true
        unknown_cost_value: 0
        trinary_costmap: True
        transform_tolerance: 0.3

      # voxel_layer:
      #   plugin: "nav2_costmap_2d::VoxelLayer"
      #   enabled: True
      #   footprint_clearing_enabled: True
      #   max_obstacle_height: 2.0
      #   z_voxels: 20
      #   origin_z: 0.0
      #   z_resolution: 0.10
      #   unknown_threshold: 19
      #   publish_voxel_map: True
      #   mark_threshold: 2
      #   combination_method: 1
      #   publish_voxel_map: True

      #   # from obstacle_layer
      #   track_unknown_space: False
      #   transform_tolerance: 0.3
      #   observation_sources: pointcloud
      #   pointcloud:
      #     topic: /rslidar_points
      #     sensor_frame: rslidar
      #     observation_persistence: 0.0
      #     expected_update_rate: 0.3
      #     data_type: "PointCloud2"
      #     min_obstacle_height: 0.1
      #     max_obstacle_height: 2.0
      #     marking: True
      #     clearing: True
      #     obstacle_range: 2.5
      #     raytrace_range: 3.0

      stvl_obstacle_layer:
        plugin: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"
        enabled: true
        observation_sources:   rslidar_points
        transform_tolerance:   0.3    # seconds  
        enabled:               true
        publish_voxel_map:     true   # default off  
        voxel_size:            0.1   #meters
        combination_method:    1      #1=max, 0=override
        mark_threshold:        0      #voxel height
        update_footprint_enabled: true
        track_unknown_space:   false   #default space is unknown
        decay_model:           0      #0=linear, 1=exponential, -1=persistent
        voxel_decay:           0.3     #seconds if linear, e^n if exponential
        mapping_mode:          false  # default off, saves map not for navigation
        map_save_duration:     60.0     #default 60s, how often to autosave

        rslidar_points:
          topic: /rslidar_points
          sensor_frame: rslidar
          observation_persistence: 0.5  #default 0, use all measurements taken during now-value, 0=latest 
          expected_update_rate: 0.1     #default 0, if not updating at this rate at least, remove from buffer
          data_type: PointCloud2
          min_obstacle_height: 0.15      #default 0, meters
          max_obstacle_height: 1.20      #defaule 3, meters
          inf_is_valid: false           #default false, for laser scans    
          marking: true
          clearing: false
          min_z: 0.2
          max_z: 3.0
          vertical_fov_angle: 0.56
          vertical_fov_padding: 0.0
          horizontal_fov_angle: 6.29
          decay_acceleration: 5.0
          filter: voxel               #default passthrough, apply "voxel", "passthrough", or no filter to sensor data, recommended to have at one filter on
          voxel_min_points: 0           #default 0, minimum points per voxel for voxel filter
          clear_after_reading: false    #default false, clear the buffer after the layer gets readings from it
          enabled: true
          model_type: 1
          obstacle_range: 4.0           #meters

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.3
        cost_scaling_factor: 10.0
        inflate_unknown: False
        inflate_around_unknown: False

planner_server:
  ros__parameters:
    use_sim_time: False
    expected_planner_frequency: 5.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 1.0
      use_astar: false
      allow_unknown: true

# controller_server:
#   ros__parameters:
#     use_sim_time: True
#     controller_frequency: 5.0
#     progress_checker_plugin: "progress_checker" # progress_checker_plugin: "progress_checker" For Humble and older
#     goal_checker_plugin: "goal_checker"
#     controller_plugins: ["FollowPath"]    
#     min_x_velocity_threshold: 0.001
#     min_y_velocity_threshold: 0.1
#     min_theta_velocity_threshold: 0.001
#     odom_topic: "leg_odom2"

#     progress_checker:
#       plugin: "nav2_controller::SimpleProgressChecker"
#       required_movement_radius: 0.5
#       movement_time_allowance: 10.0
#     goal_checker:
#       plugin: "nav2_controller::SimpleGoalChecker"
#       xy_goal_tolerance: 0.25
#       yaw_goal_tolerance: 0.25
#       stateful: True

#     # FollowPath:
#     #   plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
#     #   desired_linear_vel: 0.6
#     #   lookahead_dist: 0.8

#     #   min_lookahead_dist: 0.3
#     #   max_lookahead_dist: 1.5
#     #   lookahead_time: 1.5
#     #   use_velocity_scaled_lookahead_dist: True

#     #   rotate_to_heading_angular_vel: 0.6
#     #   transform_tolerance: 0.3
#     #   min_approach_linear_velocity: 0.05
#     #   use_approach_linear_velocity_scaling: True
#     #   # max_allowed_time_to_collision:    
#     #   use_regulated_linear_velocity_scaling: True
#     #   use_cost_regulated_linear_velocity_scaling: true
#     #   cost_scaling_dist: 0.6
#     #   # cost_scaling_gain: 
#     #   # inflation_cost_scaling_factor: 
#     #   regulated_linear_scaling_min_radius: 0.9
#     #   regulated_linear_scaling_min_speed: 0.05
#     #   use_rotate_to_heading: True
#     #   rotate_to_heading_min_angle: 0.5
#     #   max_angular_accel: 0.6
#     #   goal_dist_tol: 0.20

#     FollowPath:
#       plugin: "dwb_core::DWBLocalPlanner"
#       min_vel_x: 0.0
#       min_vel_y: 0.0
#       max_vel_x: 1.0
#       max_vel_y: 0.2
#       max_vel_theta: 0.6
#       min_speed_xy: 0.0
#       max_speed_xy: 1.0
#       min_speed_theta: 0.0
#       acc_lim_x: 1.0
#       acc_lim_y: 0.2
#       acc_lim_theta: 0.6
#       decel_lim_x: -1.0
#       decel_lim_y: -0.2
#       decel_lim_theta: -0.6

#       vx_samples: 21
#       vy_samples: 5
#       vtheta_samples: 23 

#       sim_time: 3.0
#       discretize_by_time: False 
#       # time_granularity: 
#       linear_granularity: 0.1
#       angular_granularity: 0.05
#       # include_last_point:

#       # sim_period:

#       # critics: ["PreferForward", "GoalDist", "PathAlign", "GoalAlign", "PathDist", "Oscillation", "RotateToGoal", "BaseObstacle", "ObstacleFootprint", "Twirling"]
#       critics: ["PreferForward", "GoalDist", "PathDist", "RotateToGoal", "BaseObstacle"]
#       # default_critic_namespaces:

#       # PreferForward.class:
#       PreferForward.scale: 80.0
#       # PreferForward.penalty: 
#       PreferForward.strafe_x: 0.3
#       PreferForward.strafe_theta: 0.3
#       PreferForward.theta_scale: 1.0

#       # GoalDist.class:
#       GoalDist.scale: 60.0
#       GoalDist.aggregation_type: "last"

#       # PathAlign.class:
#       PathAlign.scale: 80.0
#       PathAlign.aggregation_type: "sum"
#       PathAlign.forward_point_distance: 0.3

#       # GoalAlign.class:
#       GoalAlign.scale: 48.0
#       GoalAlign.aggregation_type: "last"
#       GoalAlign.forward_point_distance: 0.3

#       # PathDist.class:
#       PathDist.scale: 20.0
#       PathDist.aggregation_type: "sum"

#       # Oscillation.class:
#       # Oscillation.scale:
#       # Oscillation.oscillation_reset_dist:
#       # Oscillation.oscillation_reset_angle:
#       # Oscillation.oscillation_reset_time:
#       # Oscillation.x_only_threshold:

#       # RotateToGoal.class:
#       RotateToGoal.scale: 32.0
#       xy_goal_tolerance: 0.25
#       trans_stopped_velocity: 0.05
#       RotateToGoal.slowing_factor: 5.0
#       RotateToGoal.lookahead_time: -1.0

#       # BaseObstacle.class:
#       BaseObstacle.scale: 0.02
#       # BaseObstacle.sum_scores:

#       # ObstacleFootprint.class:
#       # ObstacleFootprint.scale:
#       # ObstacleFootprint.max_scaling_factor:
#       # ObstacleFootprint.scaling_speed:

#       # Twirling.class:
#       # Twirling.scale:

#       # prune_plan:
#       # prune_distance:
#       # debug_trajectory_details:
#       # trajectory_generator_name:
#       transform_tolerance: 0.2
#       # shorten_transformed_plan:
#       short_circuit_trajectory_evaluation: True

#       publish_evaluation: True
#       publish_global_plan: True
#       publish_transformed_plan: True
#       publish_local_plan: True
#       publish_trajectories: True
#       publish_cost_grid_pc: True
#       # marker_lifetime:

controller_server:
  ros__parameters:
    use_sim_time: True
    controller_frequency: 5.0
    progress_checker_plugin: "progress_checker" # progress_checker_plugin: "progress_checker" For Humble and older
    goal_checker_plugin: "goal_checker"
    controller_plugins: ["FollowPath"]    
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.1
    min_theta_velocity_threshold: 0.001
    odom_topic: "leg_odom2"

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.4
      yaw_goal_tolerance: 0.4
      stateful: True

    # FollowPath:
    #   plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
    #   desired_linear_vel: 0.6
    #   lookahead_dist: 0.8

    #   min_lookahead_dist: 0.3
    #   max_lookahead_dist: 1.5
    #   lookahead_time: 1.5
    #   use_velocity_scaled_lookahead_dist: True

    #   rotate_to_heading_angular_vel: 0.6
    #   transform_tolerance: 0.3
    #   min_approach_linear_velocity: 0.05
    #   use_approach_linear_velocity_scaling: True
    #   # max_allowed_time_to_collision:    
    #   use_regulated_linear_velocity_scaling: True
    #   use_cost_regulated_linear_velocity_scaling: true
    #   cost_scaling_dist: 0.6
    #   # cost_scaling_gain: 
    #   # inflation_cost_scaling_factor: 
    #   regulated_linear_scaling_min_radius: 0.9
    #   regulated_linear_scaling_min_speed: 0.05
    #   use_rotate_to_heading: True
    #   rotate_to_heading_min_angle: 0.5
    #   max_angular_accel: 0.6
    #   goal_dist_tol: 0.20

    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      min_vel_x: -0.02
      min_vel_y: -0.02
      max_vel_x: 1.0
      max_vel_y: 0.2
      max_vel_theta: 0.8
      min_speed_xy: 0.01
      max_speed_xy: 1.0
      min_speed_theta: 0.01
      acc_lim_x: 1.0
      acc_lim_y: 0.2
      acc_lim_theta: 0.8
      decel_lim_x: -1.0
      decel_lim_y: -0.2
      decel_lim_theta: -0.8

      vx_samples: 20
      vy_samples: 6
      vtheta_samples: 40

      sim_time: 3.0
      discretize_by_time: False 
      # time_granularity: 
      linear_granularity: 0.1
      angular_granularity: 0.1
      # include_last_point:

      # sim_period:

      # critics: ["PreferForward", "GoalDist", "PathAlign", "GoalAlign", "PathDist", "Oscillation", "RotateToGoal", "BaseObstacle", "ObstacleFootprint", "Twirling"]
      critics: ["PreferForward", "GoalDist", "PathDist", "RotateToGoal", "BaseObstacle"]
      # default_critic_namespaces:

      # PreferForward.class:
      PreferForward.scale: 40.0
      # PreferForward.penalty: 
      PreferForward.strafe_x: 0.3
      PreferForward.strafe_theta: 0.3
      PreferForward.theta_scale: 1.0

      # GoalDist.class:
      GoalDist.scale: 60.0
      GoalDist.aggregation_type: "last"

      # PathAlign.class:
      PathAlign.scale: 40.0
      PathAlign.aggregation_type: "sum"
      PathAlign.forward_point_distance: 0.1

      # GoalAlign.class:
      GoalAlign.scale: 48.0
      GoalAlign.aggregation_type: "last"
      GoalAlign.forward_point_distance: 0.1

      # PathDist.class:
      PathDist.scale: 20.0
      PathDist.aggregation_type: "sum"

      # Oscillation.class:
      # Oscillation.scale:
      # Oscillation.oscillation_reset_dist:
      # Oscillation.oscillation_reset_angle:
      # Oscillation.oscillation_reset_time:
      # Oscillation.x_only_threshold:

      # RotateToGoal.class:
      RotateToGoal.scale: 32.0
      xy_goal_tolerance: 0.4
      trans_stopped_velocity: 0.05
      RotateToGoal.slowing_factor: 5.0
      RotateToGoal.lookahead_time: -1.0

      # BaseObstacle.class:
      BaseObstacle.scale: 0.02
      # BaseObstacle.sum_scores:

      # ObstacleFootprint.class:
      # ObstacleFootprint.scale:
      # ObstacleFootprint.max_scaling_factor:
      # ObstacleFootprint.scaling_speed:

      # Twirling.class:
      # Twirling.scale:

      # prune_plan:
      # prune_distance:
      # debug_trajectory_details:
      # trajectory_generator_name:
      transform_tolerance: 0.2
      # shorten_transformed_plan:
      short_circuit_trajectory_evaluation: True

      publish_evaluation: True
      publish_global_plan: True
      publish_transformed_plan: True
      publish_local_plan: True
      publish_trajectories: True
      publish_cost_grid_pc: True
      # marker_lifetime:

map_server:
  ros__parameters:
    use_sim_time: False
    yaml_filename: "/home/ysc/lite_cog_ros2/system/map/lite3.yaml"
    topic_name: "map"
    frame_id: "map"

recoveries_server:
  ros__parameters:
    use_sim_time: False
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 1.0
    recovery_plugins: ["spin", "backup", "wait"]
    spin:
      plugin: "nav2_recoveries/Spin"
    backup:
      plugin: "nav2_recoveries/BackUp"
    wait:
      plugin: "nav2_recoveries/Wait"
    global_frame: map
    robot_base_frame: base_link
    transform_tolerance: 0.3
    simulate_ahead_time: 2.0
    max_rotational_vel: 1.0
    min_rotational_vel: 0.3
    rotational_acc_lim: 1.0
